import { useEffect, useRef, useState } from 'react';
import evidence from '../data/onchain.json' with { type: 'json' };
import { readArc, usdc } from '../data/arc-read.ts';
import type { ArcReading } from '../data/arc-read.ts';
import './onchain.css';
export function OnchainPanel({onClose}:{onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [live,setLive]=useState<ArcReading>(),[loading,setLoading]=useState(true);
  useEffect(()=>{
    dialog.current?.showModal(); const controller=new AbortController();
    const timeout=setTimeout(()=>controller.abort(),12000);
    readArc(controller.signal).then(setLive).catch(()=>{}).finally(()=>{clearTimeout(timeout);if(!controller.signal.aborted) setLoading(false);});
    const abort=()=>setLoading(false);controller.signal.addEventListener('abort',abort);
    return()=>{controller.signal.removeEventListener('abort',abort);controller.abort();clearTimeout(timeout);dialog.current?.close();};
  },[]);
  return <dialog ref={dialog} className="onchain-panel" aria-labelledby="arc-title" onCancel={onClose} onKeyDown={e=>e.stopPropagation()}>
    <header><span className="eyebrow">VERIFY ON ARC</span><button onClick={onClose} aria-label="Close Verify on Arc">Close</button></header>
    <h2 id="arc-title">10 USDC of principal settled 40 USDC of invoices across four suppliers on Arc testnet; every receipt below.</h2>
    <p className="arc-boundary">The globe plays a year generated by the reference implementation; this panel is the Arc testnet vault.</p>
    <p>Chain ID {evidence.chainId} · <a href={evidence.sourceUrl} target="_blank" rel="noreferrer">Verified vault source</a><br/><code className="arc-address">{evidence.vault}</code></p>
    <section className="arc-balances" aria-label="Vault balances"><h3>{live?'live from Arc testnet':'recorded'}{loading?' · checking Arc…':''}</h3>
      {live&&<p><time dateTime={live.timestamp}>{new Date(live.timestamp).toLocaleString('en-US',{timeZone:'America/New_York'})} ET</time> · block {BigInt(live.block).toString()}</p>}
      <dl><div><dt>Vault USDC balance</dt><dd>{usdc(live?.usdc??evidence.recorded.usdc)} USDC</dd></div><div><dt>Total principal supply</dt><dd>{usdc(live?.totalSupply??evidence.recorded.principal)} USDC</dd></div>
      {(live?live.supplies.map(s=>({label:`${new Date(s.id*86400000).toISOString().slice(0,10)} · ID ${s.id}`,amount:s.amount})):evidence.recorded.supplies.map(s=>({label:`Run day +${s.offset}`,amount:s.amount}))).map(s=><div key={s.label}><dt>Dated supply · {s.label}</dt><dd>{usdc(s.amount)} USDC</dd></div>)}</dl>
      {!live&&!loading&&<p>Arc RPC unavailable. Showing the recorded demo balances.</p>}
      <p className="arc-check">Recorded final balance-sheet check: deficit {usdc(evidence.recorded.deficit)} USDC · principal matched ({usdc(evidence.recorded.principal)} USDC).</p>
    </section>
    <details><summary>Five recorded actors and roles</summary><ul className="arc-actors">{evidence.actors.map(a=><li key={a.address}><strong>{a.name}</strong> · {a.role}<br/><a className="arc-address" href={a.url} target="_blank" rel="noreferrer">{a.address}</a></li>)}</ul></details>
    <h3>Every receipt · 16 transactions</h3><div className="arc-table"><table><thead><tr><th>Step</th><th>Amount</th><th>Dated-unit date</th><th>Receipt</th></tr></thead><tbody>{evidence.transactions.map(t=><tr key={t.hash}><td>{t.step}. {t.label}</td><td>{t.amount} USDC</td><td>{t.date??'—'}</td><td><a href={t.url} target="_blank" rel="noreferrer">Explorer<span className="sr-only">: {t.label}</span></a></td></tr>)}</tbody></table></div>
    <p>Dates are relative to the recorded run day. Funding and approval do not mint dated units. <a href={evidence.reportUrl} target="_blank" rel="noreferrer">Recorded run report</a></p>
    <section><h3>Try it</h3><p>Deploy your own testnet vault using the setup instructions, fund its checkpoint owner with testnet USDC, and set <code>ARC_DEPLOYER_KEY</code> in your environment. Replace <code>&lt;testnet-seed&gt;</code> with your own seed.</p><pre><code>{evidence.command}</code></pre><p>This command sends testnet transactions. The current script follows the updated display chain; the receipts above preserve the original run.</p><p><a href={evidence.faucet} target="_blank" rel="noreferrer">Circle testnet faucet</a> · <a href={evidence.readmeUrl} target="_blank" rel="noreferrer">Setup and live-run prerequisites</a> · <a href="/architecture">Architecture</a></p></section>
  </dialog>;
}
