import type { PlaybackEngine, PlaybackState } from '../playback/engine.ts';
import { activeChecks, curveQuotes, latestEvent, rationalDollars } from '../data/overlay-selectors.ts';
import { COIN_BEATS, COMPOSABLE_BEATS, SHOTS, beatIndex } from './shots.ts';
import { displayDate } from '../data/types.ts';


export function ShotOverlays({ engine, state, onVerify }: { engine: PlaybackEngine; state: PlaybackState; onVerify?: () => void }) {
  const shot=state.shot, scene=SHOTS.find(s=>s.id===shot);if(!scene||['none','title','descent','line'].includes(scene.overlay))return null;
  const event = latestEvent(engine.index, state.day, state.cursor), seq = event?.seq ?? 0;
  const coinBeat = COIN_BEATS[beatIndex(COIN_BEATS,state.shotElapsed)];
  const progress = Math.min(1, Math.max(0, (state.shotElapsed - 24) / 12));
  const from=30;
  const to=90;
  const date = Math.round(from + (to - from) * progress);
  const quotes = curveQuotes(engine.index, seq), available = quotes.filter(q => q.price !== null);
  const minimum = Math.min(0.95, ...available.map(q => q.price!)), maximum = Math.max(1, ...available.map(q => q.price!));
  const x = (tenor: number) => 75 + tenor / 180 * 670;
  const y = (price: number) => 255 - (price - minimum) / Math.max(0.01, maximum - minimum) * 200;
  const checks = activeChecks(event), sheet = event?.balanceSheet ?? {};
  const cube = shot === 10 && state.stage === 'cube';
  const appUrl = import.meta.env.VITE_PUBLIC_APP_URL || new URL(import.meta.env.BASE_URL, location.href).href;
  return <div className={`shot-overlay ${cube ? 'cube-overlay' : ''} scene-overlay-${scene.overlay}`} data-testid={`overlay-${shot}`}>
    <div className="globe-dimmer" style={{opacity:shot===2?Math.min(1,Math.max(0,(state.shotElapsed-5.3)/.6)):1}} />
    {shot===2&&<section className="overlay-card network-card" style={{opacity:Math.min(1,Math.max(0,(state.shotElapsed-5.3)/.6))}}><span className="eyebrow">A GLOBAL SUPPLY CHAIN</span><h2>$194B / year</h2><p>~200 companies · thousands of factories · 50+ countries</p></section>}
    {shot===15&&<section className="overlay-card catch-card"><span className="eyebrow">115-DAY SUPPLIER TERMS</span><h2>$56 billion</h2><p>Purchase obligations.<br/>Committed. Not yet paid.</p></section>}
    {shot === 6 && <section className={`overlay-card coin-layout coin-${coinBeat.key}`} aria-label="Dated coin" data-beat={coinBeat.key}>
      <div className="coin-copy" key={coinBeat.key}><span className="eyebrow">A DOLLAR WITH A DATE</span><h2>{coinBeat.title}</h2><p>{coinBeat.text}</p>
        {state.shotElapsed>=24&&state.shotElapsed<38&&<div className="coin-extension"><div className="date-interval"><span>DAY 30</span><span className="interval-line"/><span>DAY 90</span></div><div className="yield-track"><div style={{width:`${progress*100}%`}}/></div><div className="meter-label"><span>{Math.round(60*progress)} added days</span><span>Yield for this interval</span></div></div>}
        {coinBeat.key==='claim'&&<div className="claim-rule">Earlier date ≤ bill due date</div>}
        {state.shotElapsed>=44&&<div className="asset-composition"><b>USDC</b><span>→</span><b>Arc vault</b>{state.shotElapsed>=49&&<><span>←</span><b>USYC <small>yield source</small></b></>}</div>}
      </div>
      <div className="coin-stage"><div className="dated-coin"><span>CASCADE</span><strong>$1</strong>{state.shotElapsed>=6&&<><div className="coin-date">{displayDate(date)}</div><small>DAY {date}</small></>}</div>
      {coinBeat.key==='fungibility'&&<div className="dated-coin twin-coin"><strong>$1</strong><div className="coin-date">{displayDate(date)}</div><span>Same date</span></div>}
      {coinBeat.key==='claim'&&<div className="ghost-bill"><span>SUPPLIER BILL</span><strong>$1</strong><span>DAY 90 · PAID AT FACE</span></div>}</div>
      {state.shotElapsed>=38&&<div className="curve-ghost" aria-label="Market curve preview"/>}
    </section>}
    {shot===17&&<section className="overlay-card treasury-card"><span className="eyebrow">NOW YOU’RE THE TREASURER</span><h2>{state.shotElapsed<4?'Two dates.':'Who gets the yield?'}</h2><div className="treasury-dates"><div><strong>$1</strong><span>Arrives in 30 days</span></div><div className={`treasury-gap ${state.shotElapsed>=4?'gap-highlight':''}`}>{state.shotElapsed>=4?'60 days of yield':'→'}</div><div style={{opacity:state.shotElapsed>=2?1:0}}><strong>$1</strong><span>Bill due in 90 days</span></div></div><div className="curve-ghost"/><div className="yield-axis-bridge" style={{opacity:state.shotElapsed>=4?1:0,transform:'rotate(90deg)'}}/></section>}
    {shot === 7 && <section className="overlay-card curve-card" aria-label="Yield curve"><div className="yield-axis-bridge" style={{opacity:Math.max(0,1-state.shotElapsed/1.2),transform:`rotate(${90*(1-Math.min(1,state.shotElapsed/.6))}deg)`}}/><span className="eyebrow">THE PRICE OF COMMERCIAL TIME</span><h2>A yield curve.<br />From a payment rail.</h2><div className="curve-label">DOLLARS PAID PER $1 FACE VALUE</div><svg viewBox="0 0 820 310" role="img" aria-label="Dated-dollar prices for 7, 30, 60, 90 and 180 days">
      {[0, 1, 2].map(i => { const price = minimum + (maximum - minimum) * i / 2; return <g key={i}><line x1="65" x2="770" y1={y(price)} y2={y(price)} className="curve-grid" /><text x="0" y={y(price) + 5}>{price.toFixed(3)}</text></g>; })}
      {quotes.map((q, i) => <g key={q.tenor} style={{opacity:state.shotElapsed>=.6+i*.8?1:0,transition:'opacity 300ms'}}>{q.price !== null && <><circle cx={x(q.tenor)} cy={y(q.price)} r="5" /><text x={x(q.tenor)} y={y(q.price) - 16} textAnchor="middle">{q.price.toFixed(4)}</text>{i > 0 && quotes[i - 1].price !== null && <line className="curve-line" x1={x(quotes[i - 1].tenor)} y1={y(quotes[i - 1].price!)} x2={x(q.tenor)} y2={y(q.price)} />}</>}<text x={x(q.tenor)} y="298" textAnchor="middle">{q.tenor}d</text></g>)}
    </svg>{!available.length && <p className="curve-empty">Awaiting discount-window trades</p>}<p className="fine-print">Face-weighted executed prices · through {displayDate(state.day, true)}</p></section>}
    {shot === 8 && <section className="overlay-card laws-card" aria-label="Conservation laws"><span className="eyebrow">THREE CONSERVATION LAWS</span><h2>Nothing counted twice.</h2><div className="law"><span>01 / PRINCIPAL</span><strong>Backing ≥ dated units + spot + accrued yield</strong></div><div className="law"><span>02 / YIELD</span><strong>Every dollar of income has exactly one owner.</strong><p>Yield intervals on the same principal never overlap.</p></div><div className="law"><span>03 / LOSS</span><strong>Reserve first. Then the day’s income.</strong><p>Never principal.</p></div></section>}
    {shot === 9 && <section className="overlay-card vault-card" aria-label="Vault balance sheet"><span className="eyebrow">THE VAULT / {displayDate(state.day).toUpperCase()}</span><h2>Every dollar.<br />Accounted for.</h2><div className="vault-columns"><dl>{[['Backing', 'backing_value_cents'], ['Dated units', 'dated_cents'], ['Spot', 'spot_cents'], ['Accrued yield', 'unclaimed_accrued_cents'], ['Reserve', 'reserve_cents'], ['Deficit', 'deficit_cents']].map(([label, field]) => <div key={field}><dt>{label}</dt><dd>{rationalDollars(sheet[field])}</dd></div>)}</dl><div className="invariant-list"><span className="eyebrow">INVARIANTS</span>{checks.hard.map(c => <div key={c.name} className={c.pass ? 'check-pass' : 'check-fail'}><span className="check-light" />{c.name.replaceAll('_', ' ')}</div>)}{!checks.hard.length && <p>Awaiting a vault checkpoint</p>}{checks.breaches.filter(c => c.active).map(c => <div className="check-fail" key={c.name}><span className="check-light" />{c.name.replaceAll('_', ' ')}</div>)}</div></div><p className="fine-print">Claimable yield {rationalDollars(sheet.claimable_cents)} is included in accrued yield.</p></section>}
    {(shot === 11 || shot===18) && <section className="overlay-card architecture-card" aria-label="Architecture"><span className="eyebrow">DATED DOLLARS ON ARC</span><h2>{shot===18?'Money with a date.':'Composable.'}</h2><ol className="composable-items">{COMPOSABLE_BEATS.map((beat,i)=><li key={beat.title} className={(shot===18||state.shotElapsed>=beat.at)?'beat-visible':'beat-pending'} aria-hidden={shot!==18&&state.shotElapsed<beat.at} data-reveal-at={beat.at}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{beat.title}</strong><p>{beat.detail}</p></div></li>)}</ol><a href={`${import.meta.env.BASE_URL}architecture.svg`} download>Download architecture diagram</a></section>}
    {shot === 12 && <section className="overlay-card close-card" aria-label="Cascade close card"><h2 className={state.shotElapsed>=1?'close-wordmark beat-visible':'close-wordmark beat-pending'}><svg className="wordmark-icon" viewBox="0 0 36 36" aria-hidden="true"><path d="M5 8h26M5 18h19M5 28h12" stroke="currentColor" strokeWidth="4"/></svg>Cascade Money</h2><p style={{opacity:state.shotElapsed>=6?1:0,transition:'opacity 1s'}}>money with a date.</p><nav aria-label="Cascade links" style={{opacity:state.shotElapsed>=8?1:0,transition:'opacity 1s'}}><button className="onchain-trigger" onClick={onVerify}>Verify on Arc</button><a href="/architecture">Architecture</a><a href={appUrl}>Open the app <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg></a><a href="https://github.com/mcorrig4/cascade-money" target="_blank" rel="noreferrer">Repository <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg></a><a href="https://testnet.arcscan.app/address/0x57838a35f05a43ad519204d7a6ce63f52d7c1987#code" target="_blank" rel="noreferrer">Arc contract <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg></a></nav><div className="close-footer"><span>{import.meta.env.VITE_TEAM || 'Cascade team'}</span><span>Earth imagery: NASA</span></div></section>}
  </div>;
}
